title: Bartosz Bonisławski # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Fullstack Ruby Developer
  <br><br>
  Available to hire
  <br><br>
  <a href="https://www.linkedin.com/in/bartosz-bonisławski-77816a103">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-11904710-8 # your Google Analytics tracking ID here
